### ISSUE TITLE
Port Qt applet to Qt5

### ISSUE THREAD

**Issue by ShalokShalom** [t-woerner/firewalld#155] opened 2016-09-08 22:15 UTC
Hi there :)

Since some of you might know, is there - as it seems - not a single one maintained qt5 GUI for firewall configuration. 

Any interests to port yours to the current version?

4 is unmainted since a long time and through that, insecure.

**Comment by t-woerner** [comment] 2016-10-04 15:31
Yes, there is a plan for this - this is a duplicate of #128

**Closed** 2016-10-04 15:32 UTC
