### ISSUE TITLE
FirewallD not using NetworkManager interface zones on boot (only changes made after booting), this affects e.g. Docker

### ISSUE THREAD

**Issue by tiangolo** [t-woerner/firewalld#195] opened 2017-01-12 23:07 UTC
## Description

Changing an interface (e.g. `docker0`) zone (e.g. `trusted`) that is controlled by NetworkManager using `nmcli` updates the zone in FirewallD and creates a `ifcfg` file. Before the change, FirewallD thinks that it has `no zone`.

After a reboot, FirewallD overwrites that `ifcfg` file, removing the `ZONE` (setting it to `ZONE=`). NetworkManager then thinks that that interface has no zone, and now FirewallD assumes that the interface goes to the default (`public`) zone. Not keeping the configuration set before the reboot.

## Environment

**OS**: CentOS Linux release 7.3.1611 (Core)
**Kernel**: 4.8.6-x86_64-linode78
**FirewallD** with `firewall-cmd --version`: 0.4.3.2 (the one that cames "from a stock" CentOS 7 after a `yum update`)
**NetworkManager** with `nmcli --version`: nmcli tool, version 1.4.0-13.el7_3
**Docker** (that's my main test case) with `docker version`: 
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64
```

## Steps to reproduce and behavior

* Start with a new Linode with CentOS 7
* Update with 
```bash
yum update
```
* [Install Docker](https://docs.docker.com/engine/installation/linux/centos/#/install-with-the-script) (that's my test case to create a new interface and what I needed to solve):

```bash
curl -fsSL https://get.docker.com/ | sh
systemctl enable docker.service
systemctl start docker
```

* Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
FirewallD is not running
```

* Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        --
```

* Enable and start FirewallD:

```bash
systemctl enable firewalld.service
systemctl start firewalld.service
```

* Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
no zone
```

* Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        --
```

* At this point, there is no `ifcfg-docker0` file created:

```bash
ls /etc/sysconfig/network-scripts/ifcfg-*
```

...outputs:

```
/etc/sysconfig/network-scripts/ifcfg-eth0  /etc/sysconfig/network-scripts/ifcfg-lo
```

* And the only zone XML file in FirewallD configs is for the `public` zone:

```bash
ls /etc/firewalld/zones/
```

...outputs:

```
public.xml
```

* The first thing I tried (and most of the people probably, after learning how FirewallD should be used), would be to add `docker0` to the `trusted` zone:

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

...outputs:

```
The interface is under control of NetworkManager, setting zone to 'trusted'.
success
```

* Although it outputed `success` it still thinks that it has `no zone`. Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
no zone
```

* But NetworkManager now thinks that it is in the `trusted` zone. Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        trusted
```

...So, FirewallD was able to tell NetworkManager to put `docker0` in the `trusted` zone but was unable to see that it actually did. I don't know if that's expected behavior or if it's a different issue itself.

* And now, a `ifcfg-docker0` file was created:

```bash
cat /etc/sysconfig/network-scripts/ifcfg-docker0
```

...outputs:

```
DEVICE=docker0
STP=no
BRIDGING_OPTS=ageing_time=299
TYPE=Bridge
BOOTPROTO=none
IPADDR=172.17.0.1
PREFIX=16
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=no
NAME=docker0
UUID=5ccc8292-95a2-40d5-9ed6-ab6202fa629e
ONBOOT=no
ZONE=trusted
```

...it includes a:

```
ZONE=trusted
```

* And the only zone XML file in FirewallD configs keeps being the `public` zone:

```bash
ls /etc/firewalld/zones/
```

...outputs:

```
public.xml
```

---

* Now, if we had not tried to set the zone with `firewall-cmd` but with NetworkManager's `nmcli` something different would happen, to see that, we can do the following.

* Remove the `ifcfg-docker0` file: 

```bash
rm -f /etc/sysconfig/network-scripts/ifcfg-docker0
```
* Restart the system (or restart each of the services in the exact order, so it's easier to restart the system): 

```
shutdown -r now
```

* After that, the system's state is as if we hadn't tried to set the firewall zone. There are no configuration files and FirewallD and NetworkManager both think that the zone is not set (we can check it with the same commands above).

* Now we can try to set the firewall zone with NetworkManager's `nmcli`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

* Now FirewallD actually thinks that the zone was set to `trusted`. Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
trusted
```

* And NetworkManager also thinks that it is in the `trusted` zone. Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        trusted
```

Now it seems like NetworkManager set the zone and that FirewallD got the message and updated its state.

* And also, a `ifcfg-docker0` file was created (the same as before):

```bash
cat /etc/sysconfig/network-scripts/ifcfg-docker0
```

...outputs:

```
DEVICE=docker0
STP=no
BRIDGING_OPTS=ageing_time=299
TYPE=Bridge
BOOTPROTO=none
IPADDR=172.17.0.1
PREFIX=16
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=no
NAME=docker0
UUID=5ccc8292-95a2-40d5-9ed6-ab6202fa629e
ONBOOT=no
ZONE=trusted
```

...it includes a:

```
ZONE=trusted
```

With the results of the commands above, showing that both FirewallD and NetworkManager "know" that `docker0` is in the `trusted` zone, and the `ifcfg-docker0` file created, I would expect the settings to be saved.

* But FirewallD has this other place for configurations of zones. And the only zone XML file in FirewallD configs keeps being the `public` zone:

```bash
ls /etc/firewalld/zones/
```

...outputs:

```
public.xml
```

---

### *Here starts the strange behavior*

* Now we can reboot the system (or restart services in a specific order that I won't detail, as a simple reboot shows the issue):

```bash
shutdown -r now
```

* After the reboot, suddenly FirewallD thinks again that the `docker0` has `no zone`. Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
no zone
```

* And NetworkManager also thinks that it has no zone. But even more, it thinks that there are two connections (not just one as before) and that they both have no zone assigned. Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        --
connection.zone:                        --
```

* If we check, the file `ifcfg-docker0` file was modified by FirewallD on boot (if FirewallD was disabled, the file would be intact):

```bash
cat /etc/sysconfig/network-scripts/ifcfg-docker0
```

...outputs:

```
DEVICE=docker0
STP=no
BRIDGING_OPTS=ageing_time=299
TYPE=Bridge
BOOTPROTO=none
IPADDR=172.17.0.1
PREFIX=16
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV4_DNS_PRIORITY=100
IPV6INIT=no
NAME=docker0
UUID=c4322f4c-8f10-4271-aa0c-8c0b51e9ac4b
ONBOOT=no
ZONE=
```

...it now has a:

```
ZONE=
```

* And there is also a `.old` file with the previous configuration (before the reboot):

```bash
cat /etc/sysconfig/network-scripts/ifcfg-docker0.old
```

## Error hypothesis

* Checking my FirewallD Systemd's Unit file, with:

```bash
cat /usr/lib/systemd/system/firewalld.service
```

...outputs:

```
[Unit]
Description=firewalld - dynamic firewall daemon
Before=network.target
Before=libvirtd.service
Before=NetworkManager.service
After=dbus.service
After=polkit.service
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service
Documentation=man:firewalld(1)

[Service]
EnvironmentFile=-/etc/sysconfig/firewalld
ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS
ExecReload=/bin/kill -HUP $MAINPID
# supress to log debug and error output also to /var/log/messages
StandardOutput=null
StandardError=null
Type=dbus
BusName=org.fedoraproject.FirewallD1

[Install]
WantedBy=basic.target
Alias=dbus-org.fedoraproject.FirewallD1.service
```

...I see that it says that it should go `Before=NetworkManager.service`, but if it starts before, it won't be able to get NetworkManager's zone configurations. 

And as [per FirewallD documentation](http://www.firewalld.org/documentation/man-pages/firewalld.zones.html), as I understand, it will overwrite (I'm not sure what for) the network interfaces not handled by NetworkManager... and if NetworkManager is not telling anything (because it is not ready yet) I guess that FirewallD will assume that the interfaces are not handled by NetworkManager and will overwrite them.

I tried changing the Systemd dependencies by creating a file in:

```
/etc/systemd/system/firewalld.service
```

with:

```
[Unit]
Description=firewalld - dynamic firewall daemon
Before=network.target
Before=libvirtd.service
Wants=NetworkManager.service
After=NetworkManager.service
After=dbus.service
After=polkit.service
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service
Documentation=man:firewalld(1)

[Service]
EnvironmentFile=-/etc/sysconfig/firewalld
ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS
ExecReload=/bin/kill -HUP $MAINPID
# supress to log debug and error output also to /var/log/messages
StandardOutput=null
StandardError=null
Type=dbus
BusName=org.fedoraproject.FirewallD1

[Install]
WantedBy=basic.target
Alias=dbus-org.fedoraproject.FirewallD1.service
```

With the main changes being:

```
Wants=NetworkManager.service
After=NetworkManager.service
```

But the problem seemed to persist intact, so, my current hypothesis is that even if FirewallD was started after NetworkManager, NetworkManager is not having enough time to start / publish it's D-Bus interfaces / connections and their zones.

## Current workaround

My current workaround is to end up with a `trusted.xml` file AND a `ifcfg-docker0` file. The `trusted.xml` file would set the zone after a reboot and the `ifcfg-docker0` would set the zone after reload or restart of services and interface or connections restarted.

To achieve that:

* After having the new interface (e.g. after installing Docker) and having FirewallD enabled and started, set the zone of the interface with NetworkManager's `nmcli`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

...that would set the zone in NetworkManager and FirewallD for the current session and will create the `ifcfg-docker0` file for services, network or interfaces' restarts and reloads.

* Now we need FirewallD to generate that `trusted.xml` file so that it uses it while booting, but for FirewallD to write that file it must think that NetworkManager is not active, so stop NetworkManager:

```bash
systemctl stop NetworkManager.service
```

* Now we can run the same command we ran at the beginning to set the zone with FirewallD's `firewall-cmd`:

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

* But this time, as NetworkManager is stopped, it won't modify (or even try to create) a `ifcfg-docker0` file, this time it will create a file in the other place for configurations, we can see it with:

```bash
cat /etc/firewalld/zones/trusted.xml
```

...outputs:

```
<?xml version="1.0" encoding="utf-8"?>
<zone target="ACCEPT">
  <short>Trusted</short>
  <description>All network connections are accepted.</description>
  <interface name="docker0"/>
</zone>
```

...we can see that the `docker0` interface was added to this `trusted` zone by the:

```
<interface name="docker0"/>
```

* And now we can start NetworkManager again:

```bash
systemctl start NetworkManager.service
```

* We can check that FirewallD thinks that the `docker0` is in the `trusted` zone. Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
trusted
```

* And NetworkManager also thinks that it is in the `trusted` zone. Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        --
connection.zone:                        trusted
connection.zone:                        trusted
```

* We can restart the system and check that the zone will persist, for both FirewallD and NetworkManager.

### Additional NetworkManager's "connections"

* I still don't know when, but at some points NetworkManager creates additional connections:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        --
connection.zone:                        trusted
connection.zone:                        trusted
```

* And it also creates files for them:

```
/etc/sysconfig/network-scripts/ifcfg-docker0     /etc/sysconfig/network-scripts/ifcfg-docker0.old
/etc/sysconfig/network-scripts/ifcfg-docker0-1  /etc/sysconfig/network-scripts/ifcfg-docker0-2
```

I still don't know what side effects that could create.

### Unsaved changes after restart

Using my workaround can also lead to unexpected errors for someone that doesn't know all what happened.

* For example, lets imagine that we decide that we want the `docker0` interface to be as it was before, by default, and we remove the `ifcfg-docker*` files:

```bash
rm /etc/sysconfig/network-scripts/ifcfg-docker0*
```

* And we restart the `network` service:

```bash
systemctl restart network.service
```

* And NetworkManager thinks that `docker0` has no zone. Check the zone of the `docker0` interface as seen by NetworkManager:

```bash
nmcli connection show docker0 | grep zone
```

...outputs:

```
connection.zone:                        --
```

* But FirewallD still thinks that `docker0` is in the `trusted` zone. Check the zone of the `docker0` interface as seen by FirewallD:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

...outputs:

```
trusted
```

* We can even restart the system and FirewallD will still think that that `docker0` is in the `trusted` zone, as it already has the `trusted.xml` file created, no matter what changes in the `ifcfg` files.

**Comment by msanabria** [comment] 2017-01-17 04:19
I confirmed this behavior on CentOS 7.2.1511 and CentOS 7.3.1611.

No matter what combination of NetworkManager or firewalld commands that I used to keep the zones persistent, nothing seemed to work. I tried the "workaround" listed above and still nothing. Here's the workaround that I came up with for my use case.

I have the follow interfaces that should be part of the corresponding zones persistently:
enp0s3 - public
enp0s8 - internal
enp0s9 - external

I created a systemd unit file as a temporary fix to my troubles:
**/etc/systemd/system/myzones.service**
```
[Unit]
Description=Custom Zones
After=network.target network.service

[Service]
Type=oneshot
User=root
Group=root
ExecStart=/bin/nmcli connection modify enp0s3 connection.zone public
ExecStart=/bin/nmcli connection modify enp0s8 connection.zone internal
ExecStart=/bin/nmcli connection modify enp0s9 connection.zone external

[Install]
WantedBy=multi-user.target
```

Only issue I ran into so far is if you try and restart the `network.service` when there are `ifcfg-*.old` files residing in `/etc/sysconfig/network-scripts/`. But a reboot will sort that out. I don't use the network service so I can live with this temporary fix for now.

**Comment by c0ntr1but3** [comment] 2017-01-17 09:07
I can also vouch for this issue.  I followed the work around above but unfortunately it only worked for one of the two interfaces on the server.

When looking at eno1 I get:
`firewall-cmd --zone=OOB --list-all`
`OOB (active)`
`  target: default`
`  icmp-block-inversion: no`
`  interfaces: eno1`
`  sources:`
`  services: ssh`
`  ports:`
`  protocols:`
`  masquerade: no`
`  forward-ports:`
`  sourceports:`
`  icmp-blocks:`
`  rich rules:`

But when I do the same for eno2, the interface is always empty after a reboot or network service restart:
`firewall-cmd --zone=PublicDNS --list-all`
`PublicDNS`
`  target: default`
`  icmp-block-inversion: no`
`  interfaces:`
`  sources:`
`  services: dns`
`  ports:`
`  protocols:`
`  masquerade: no`
`  forward-ports:`
`  sourceports:`
`  icmp-blocks:`
`  rich rules:`

I also had an echo-reply added to the icmp-blocks on the PublicDNS zone but that's gone missing also.

Finally, each time I remove the /etc/sysconfig/network-scripts/ifcfg-enX.old file, it always returns.  Following that I get errors in the syslog about the eno2 not being able to move to an up state because there is a UUID conflict with the .old file for that interface.

I could REALLY use a fix for this ASAP please.  An actual fix would be preferred, rather than another work around.  Surely this can't only be affecting the 3 of us...!

**Comment by t-woerner** [comment] 2017-01-17 10:29
Please have a look at https://bugzilla.redhat.com/show_bug.cgi?id=1381314
The upstream fixes mentioned in this bug should fix the issues for you. A 7.3 z update should be available soon (https://bugzilla.redhat.com/show_bug.cgi?id=1410860).

**Comment by t-woerner** [comment] 2017-01-17 10:41
NetworkManager sends a request to firewalld to assign the interface(s) to a zone that are used by a connection early in the process to activate this connection. With NetworkManager controlling an interface, firewalld should not save any zone setting for an interface internally, because this could lead to inconsistent information about this zone setting in case of firewalld or NetworkManager restarts. Only zone settings for active connections can be seen in firewalld with this. As the zone information is part of the connection settings, firewall-cmd will redirect requests for the interfaces to NetworkManager. For interfaces that are not under control of NetworkManager, firewalld adapts the ifcfg file to have a consistend zone setting for interfaces that are created using the network service.

There have been two issues with the connection/interface handling that will be addressed with the 7.3 z stream update. At first firewalld could reset the zone setting in a reboot and it created the ifcfg backup file with the wrong extension ".old" instead of ".bak".

**Comment by c0ntr1but3** [comment] 2017-01-17 11:10
Excellent, thanks Thomas (@t-woerner)!  Outstanding work and I appreciate the update here on this issue too.

You say an update should be available soon.  That will just be installed via a "yum update" I assume?  Any idea on number of days until this is available?  Should I consider trying a manual fix?

**Comment by tiangolo** [comment] 2017-01-17 13:45
Thanks @t-woerner !

**Comment by msanabria** [comment] 2017-01-17 17:32
Thank you @t-woerner

**Comment by msanabria** [comment] 2017-01-17 19:06
I created a script to apply this patch manually:

```
#!/bin/bash

file=/usr/lib/python2.7/site-packages/firewall/core/fw_zone.py

grep '^\(\s*\)\#zone_transaction.add_post(ifcfg_set_zone_of_interface, "", interface)$' ${file} &> /dev/null

if [ ${?} -eq 0 ]; then
  echo "Patch already applied. Exiting."
  exit 0
else
  cp -f ${file} ${file}.bak
  echo "Created backup file: ${file}.bak"
  if $(sed -e 's/^\(\s*\)zone_transaction.add_post(ifcfg_set_zone_of_interface, "", interface)$/\1#zone_transaction.add_post(ifcfg_set_zone_of_interface, "", interface)/' -i ${file}); then
    echo "Patch applied!"
    exit 0
  else
    echo "Patch NOT applied. Resetting file."
    cp -f ${file}.bak ${file}
    exit 1
  fi
fi
```

**Comment by c0ntr1but3** [comment] 2017-01-18 18:30
I can confirm that this patch has been released.  I installed it about 15mins ago using `yum update`.  I did a reboot to test and everything was retained nicely.  Also, there were no new ifcfg-enX.old interfaces created!!

Nice work and thanks again!

**Comment by t-woerner** [comment] 2017-01-19 16:17
Closing the issue as it is now available in an update.

**Closed by t-woerner** 2017-01-19 16:18 UTC

**Comment by dsun29** [comment] 2017-10-06 14:25
I still have the same issue with   CentOS Linux release 7.4.1708. Is the bug supposed to be fixed already?

**Comment by msanabria** [comment] 2017-10-06 16:43
@dsun29 You'll have to get some output here because I tested one two fresh installs of CentOS 7.4.1708 and I was not able to reproduce.
